config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  get 'users/create'

  get 'home/index'

  get 'styles/atoms'

  get 'styles/molecules'

  get 'styles/organisms'

  root to: 'home#index'

  get 'acount/ideas'
  resources :users
  resources :ideas do
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/acount.rb
class Acount < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :idea
  belongs_to :user
  
end

app/models/idea.rb
 class Idea < ApplicationRecord

validates :title, presence: true
validates :title, length: {maximum: 75}
  has_many :comments
  belongs_to :user
  def self.search(search_term)
where('title LIKE?',"%#{search_term}%").or(where('migration LIKE?', "%#{search_term}%"))
end

def self.most_recent()
  all.order(created_at: :desc).limit(3)
end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comment
  has_many :idea
end

app/controllers/acount_controller.rb
class AcountController < ApplicationController
  def ideas
  @idea =Idea.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
def create
  @user =User.find(session[:user_id])
  @idea=Idea.find(params[:idea_id])
  comment=Comment.new(comment_param)
  comment.idea=@idea
  comment.user=@user
  comment.save!
  redirect_to(idea_path(@idea))
end

  private
  def comment_param
  params.require(:comment).permit(:body)
end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
      @idea =Idea.most_recent
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  def index
    @search_term = params[:q]
    logger.info("le theme de recherche est #{@search_term} ")

    @idea =Idea.search(@search_term)
  end

  def new
  @idea=Idea.new
  end

  def create
    @title = params[:title]
    logger.info(@title)
    @idea = Idea.new(idea_resource_params)
    if(@idea.save)
    redirect_to(ideas_path)
  else
    render 'new'
  end
  end


  def edit
    id=params[:id]
    @idea= Idea.find(id)
  end


  def update
    @idea=Idea.find(params[:id])
    if(@idea.update(idea_resource_params))
    redirect_to(acount_ideas_path)
  else
    render 'edit'
  end

  end


  def show
    @display_add_comment = session[:user_id].present?
@idea= Idea.find(params[:id])
@comments= Comment.new

  end

private
def idea_resource_params
  params.require(:idea).permit(:title,:photo_url,:done_count,:migration)
end


end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
  def atoms
  end

  def molecules
  end

  def organisms
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user=User.new
  end

  def create

user = User.find_or_create_by(params_user)
  session[:user_id] = user.id
  redirect_to(ideas_path)
  end

  private
  def params_user
    params.require(:user).permit(:email)
  end
end

app/helpers/acount_helper.rb
module AcountHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/styles_helper.rb
module StylesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/acount/_partial_acount.html.erb
<%   @idea.each do |item| %>
<li>
  <div class="card">
    <div class="card__thumb">
    <%= link_to(idea_path(item)) do %>
        <img src=<%= item.photo_url %> alt="Northern lights over mountain covered in snow">
        <div class="card__intro">
          <h4 class="card__title"><%= item.title %> </h4>
          <span><%= item.done_count %> have done this</span>
        </div>
      </div>
        <% end %>

    <div class="card__footer">
      <button class="btn delta" type="submit">
        <svg class="icon-delete" role="presentation">
          <use xlink:href="#"></use>
        </svg>
        Delete
      </button>
      <a class="btn delta" href=<%=  edit_idea_path(item) %>>
        <svg class="icon-edit" role="presentation">
          <use xlink:href="#"></use>
        </svg>
        Edit
      </a>
    </div>
  </div>
</li>
<% end %>

app/views/acount/ideas.html.erb
<main>
  <div class="content-wrapper">
    <div class="page-header">
      <h1>My Idea</h1>
      <%= link_to('Create Idea', new_idea_path, class: 'btn' ) %>

    </div>
  </div>
  <div class="content-wrapper">
    <ul class="bare-list float-grid css-grid">
      <%= render(partial: 'partial_acount') %>
    </ul>
  </div>
  <div class="see-more">
    <button class="btn" type="button" data-more="true">See more</button>
  </div>
</main>

app/views/application/_idea_card.html.erb
<div class="card">
  <div class="card__thumb">
      <%= link_to(idea_path(idea)) do %>
      <%= render(partial: 'idea_photo', locals: { photo_url: photo_url}) %>
      <div class="card__intro">
        <h4 class="card__title"><%= card_title %></h4>
        <span> <%= done_count %> have done this</span>
      </div>
    </div>
    <% end %>

  <div class="card__footer">
    <button class="card__btn card__like delta" data-like="see-the-northern-lights">
      <svg class="icon-heart icon-heart--liked" role="presentation">
        <use xlink:href="/images/icons/icons-defs.svg"></use>
      </svg>
      Like
    </button>
    <button class="card__btn card__add delta" data-addGoal="see-the-northern-lights">
      <svg class="icon-pluss" role="presentation">
        <use xlink:href="/images/icons/icons-defs.svg"></use>
      </svg>
      Add Goal
    </button>
  </div>
</div>

app/views/application/_idea_photo.html.erb
<% if(photo_url.nil?)%>
<img src="http://fpoimg.com/255x170" alt="Northern lights over mountain covered in snow">
  <% else %>
<img src= <%=photo_url %> alt= "Northern lights over mountain covered in snow">
     <% end %>

app/views/application/_search_form.html.erb
<%=link_to('<span><i>My</i> Bucket List</span>'.html_safe,root_path) %>
</div>
<%= form_tag(ideas_path, method: 'GET', class: 'global-search') do  %>
<div class="input-inline">
  <label class="input-group__label sr-only" for="global-search-input">Looking for inspiration?</label>
  <div class="input-row">
      <%= text_field_tag('q', nil, class: 'input-row__field',placeholder: 'e.g. Swimming with dolphins') %>

    <%= button_tag('Search',class: 'btn btn--inline btn--primary' ) %>
  </div>
</div>
<% end %>

app/views/home/index.html.erb
  <main>
  <div class="masthead">
    <div class="content-wrapper">
      <h1>Get inspired. Create your bucket list. Share.</h1>
      <form method="get" action=" ">
        <div class="input-inline">
          <label class="input-group__label" for="banner-search-input">Inspire me</label>
          <div class="input-row">
            <input id="banner-search-input" class="input-row__field" type="text" name="search" placeholder="e.g. Swimming with dolphins">
            <button class="btn btn--inline" type="submit">Search</button>
          </div>
        </div>
      </form>
    </div>
  </div>
  <div class="content-wrapper">
    <h2>Some ideas</h2>
    <ul class="bare-list float-grid css-grid">
      <% @idea.each do |title| %>
      <li>
        <%= render(partial: 'idea_card', locals: {card_title: title.title, done_count: title.done_count , photo_url: title.photo_url,idea: title}) %>
      </li>
    <% end %>
    </ul>
  </div>
  <div class="see-more">
    <button class="btn" type="button" data-more="true">See more</button>
  </div>
</main>

app/views/ideas/_form.html.erb
<% if(@idea.errors.any?) %>
  <div class="alert alert--wide">
    <%= @idea.errors.full_messages.join('<br />') %>
  </div>
<% end %>
<%= form_for(idea, html: { class: 'global-search'}) do |form| %>
<div class="input-group input-group--horizontal">
 <%= form.label(:title, class: "input-group__label")%>
  <%= form.text_field(:title, class: 'input-group__field', placeholder: 'E.g. Ride a camel')%>
</div>
<div class="input-group input-group--horizontal">
 <%= form.label(:done_count, class: "input-group__label")%>
<%= form.text_field(:done_count, class: 'input-group__field',placeholder: 'done_count' )%>
</div>
<div class="input-group input-group--horizontal">
 <%= form.label(:photo_url, class: "input-group__label")%>
<%= form.text_field(:photo_url, class: 'input-group__field',placeholder: 'photo_url' )%>
</div>
<div class="input-group input-group--horizontal">
 <%= form.label(:migration, class: "input-group__label")%>
<%= form.text_area(:migration, class: 'input-group__field',placeholder: 'description' )%>
</div>
<div class="prompt">
 <a class="prompt__cancel" href="#cancel">Cancel</a>
 <%= form.submit( class: 'btn btn--primary prompt__confirm')  %>

</div>
<% end %>

app/views/ideas/edit.html.erb
<main>
 <div class="content-wrapper">
   <h1>Modified idea</h1>

  <%=render(partial:'form', locals: { idea: @idea})%>

 </div>
</main>

app/views/ideas/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
  <main>
    <div class="content-wrapper">

      <h1>Results for   <%= @search_term %></h1>
    </div>
    <% if (@idea.any?) %>
    <div class="content-wrapper">
      <ul class="bare-list float-grid css-grid">
        <% @idea.each do |title| %>
        <li>
          <%= render(partial: 'idea_card', locals: {card_title: title.title, done_count: title.done_count, photo_url: title.photo_url,idea: title}) %>
        </li>
      <% end %>
      </ul>
    </div>

    <div class="see-more">
      <button class="btn" type="button" data-more="true">See more</button>
    </div>
    <% else %>
    <h3> No Ideas Found </h3>
    <% end %>
  </main>

</body>
</html>

app/views/ideas/new.html.erb
 <main>
  <div class="content-wrapper">
    <h1>Create new idea</h1>

    <%=render(partial:'form', locals: { idea: @idea})%>
  </div>
</main>

app/views/ideas/show.html.erb
<main>
  <div class="content-wrapper hr">
    <div class="media">
      <div class="media__figure">
          <%= render(partial: 'idea_photo', locals: { photo_url: @idea.photo_url}) %>
      </div>
      <div class="media__body">
        <div class="goal">
          <div class="goal__owner">
            <%= image_tag "/images/avatar.png" , class:"avatar", alt: "Default avatar"%>
            <p>Created by <a href="#">Frederick Rose</a></p>
          </div>
          <h1 class="gamma"><%= @idea.title  %></h1>
          <ul class="horizontal-list btn-group">
            <li>

                <%= link_to(edit_idea_path(@idea), class: "btn delta") do %>
                <svg class="icon-check icon--sm" role="presentation">
                  <!-- <use xlink:href="/images/icons/icons-defs.svg"></use> -->
                </svg>
                Edit
              <% end %>
            </li>
            <li>
              <button class="btn delta" type="button">
                <svg class="icon-heart icon--sm" role="presentation">
                  <!-- <use xlink:href="/images/icons/icons-defs.svg"></use> -->
                </svg>
                Add
              </button>
            </li>
          </ul>
          <div class="goal__intro">
            <p>
              <%=@idea.migration %>
            </p>
          </div>
          <div class="goal__meta">
            <span>Created on <time datetime="2017-08-27T03:48"> <%= @idea.created_at.strftime("%d %b %y") %> </time></span>
            <span><%= @idea.done_count %> doing this</span>
            <span><a href="#comments">3 comments</a></span>
          </div>
          <ul class="tags-list">
            <li><a href="#nature">Nature</a></li>
            <li><a href="#swimming">Swimming</a></li>
            <li>
              <a href="#travel" class="selected">
                Travel
                <i class="remove-tag">&times;</i>
              </a>
            </li>
            <li><a href="#tag4" data-filter="tag-4">Tag 4</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="content-wrapper">
    <div class="comments">
      <h2 class="comments__title">Discussion <span>3 comments</span></h2>
      <% if (@display_add_comment) %>
        <%=form_for([@idea,@comments],html: {class: "comments__input" }) do |form|%>
        <%=image_tag("/images/avatar.png" , class:"avatar", alt: "Default avatar") %>
        <div class="input-group">
          <%=form.label(:body,'Add a comment', class: "input-group__label") %>
          <%=form.text_area(:body, class: "input-group__field") %>
      </div>
        <%=form.submit('Post',class: "btn btn--primary") %>
      <% end %>
      <% end %>

      <ul class="comments__listing">

        <%= @idea.comments.each do |comment| %>
        <li class="comment">
          <%= image_tag "/images/avatar.png",class:"avatar", alt: "Default avatar" %>
          <div class="comment__body">
            <h3 class="comment__title">Tom Jenkinson <time datetime="2017-08-28T13:48"><%=comment.created_at.strftime("%d %b %y") %>
            </time></h3>
            <p><%=comment.body %></p>
          </div>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BucketList</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="site-header">
        <div class="content-wrapper">
          <div class="logo">
            <%= render(partial: 'search_form') %>
          <nav class="site-header__nav">
            <ul class="main-navigation">
              <li><a href="#nolink">Inspiration</a></li>
              <li>    <%= link_to('Acount',acount_ideas_path) %>        </li>
              <li><a href="#nolink">Log In</a></li>
            </ul>
          </nav>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="site-footer">
      <div class="content-wrapper">
        <div class="logo logo--inverted footer__logo">
          
          <%= link_to("<span><i>My</i> Bucket List</span>".html_safe, root_path) %>
        </div>
        <nav class="footer__navigation">
          <ul>
            <li><a href="#nolink">About</a></li>
              <%= link_to("Style Guide",styles_atoms_path) %>
            <li><a href="#nolink">Terms of Use</a></li>
          </ul>
        </nav>
        <p class="copyright">&copy; EPFL 2017</p>
      </div>
    </footer>
  </body>
</html>

app/views/styles/_bouton_link.html.erb
<a class="btn" href="#nolink"> <%=label %> </a>

app/views/styles/_logo.html.erb
<div class="logo">
  <a href="/"><span><i>My</i> Bucket List</span></a>
</div>
<h3>Negative logo</h3>
<p>Used on dark background, like in the site footer.</p>
<div class="sg-dark-bg">
  <div class="logo logo--inverted footer__logo">
    <a href="/"><span><i>My</i> Bucket List</span></a>
  </div>
</div>

app/views/styles/_negative_logo.html.erb
<div class="sg-dark-bg">
  <nav class="footer__navigation">
    <ul>
      <li><a href="#nolink">About</a></li>
      <li><a href="#nolink">Style Guide</a></li>
      <li><a href="#nolink">Terms of Use</a></li>
    </ul>
  </nav>
</div>

app/views/styles/_partial_link.html.erb
<% if(current == true) %>
    <li><%=link_to( title, uri,class: 'current' ) %></li>
<% else %>
<li><%=link_to( title, uri ) %></li>
<% end %>

app/views/styles/_primary_boutton.html.erb
<button class="btn btn--primary" type="button"><%= label %></button>

app/views/styles/_prompt.html.erb
<div class="prompt">
  <a class="prompt__cancel" href="#cancel">Cancel</a>
  <button class="btn btn--primary prompt__confirm" type="submit"><%= label %></button>
</div>

app/views/styles/_search_control.html.erb
<div class="input-inline">
  <label class="input-group__label" for="global-search-input">Looking for inspiration?</label>
  <div class="input-row">
    <input id="global-search-input" class="input-row__field" type="text" name="global-search" placeholder="e.g. Swimming with dolphins">
    <button class="btn btn--inline" type="submit">Search</button>
  </div>
</div>

app/views/styles/_simple_boutton.html.erb
<button class="btn" type="button"><%=label %></button>

app/views/styles/_warning_boutton.html.erb
<button class="btn btn--warning" type="button"><%= label %></button>

app/views/styles/atoms.html.erb
<main class="content-wrapper">
  <div>
    <h1>Style Guide</h1>
    <p>
      Our Style Guide is based upon the principles of Atomic design, a methodology composed of five distinct stages working together to create interface design systems in a more deliberate and hierarchical manner.
    </p>
    <nav>
      <ul class="sub-navigation">
      <%= render(partial: 'partial_link', locals: {title: 'Atoms', uri: 'atoms.html',current: true}) %>
        <%= render(partial: 'partial_link', locals: {title: 'Molecules', uri: 'molecules.html',current: false}) %>
        <%= render(partial: 'partial_link', locals: {title: 'Organisms', uri: 'organisms.html',current: false}) %>
        <li><a href="#">Templates</a></li>
        <li><a href="#">Pages</a></li>
      </ul>
    </nav>
    <h2>Atoms</h2>
    <p>
      Atoms are the basic building blocks of matter. Applied to web interfaces, atoms are our HTML tags, such as a form label, an input or a button.
    </p>
    <p>
      Atoms can also include more abstract elements like color palettes, fonts and even more invisible aspects of an interface like animations.
    </p>
    <p>
      Like atoms in nature they’re fairly abstract and often not terribly useful on their own. However, they’re good as a reference in the context of a pattern library as you can see all your global styles laid out at a glance.
    </p>
    <nav>
      <ol class="ordered-navigation">
        <li><a href="#palette">Palette</a></li>
        <li><a href="#typography">Typography</a></li>
        <li><a href="#buttons">Buttons</a></li>
        <li><a href="#forms">Form Elements</a></li>
        <li><a href="#icons">Icons</a></li>
      </ol>
    </nav>
  </div>
  <section class="sg-section" id="palette">
    <h3 class="beta">01. Palette</h3>
    <ul class="sg-palette">
      <li>
        <div data-bgColor="blue"></div>
        <p>#2c9cf2</p>
      </li>
      <li>
        <div data-bgColor="black"></div>
        <p>#192127</p>
      </li>
      <li>
        <div data-bgColor="darkest"></div>
        <p>#72797e</p>
      </li>
      <li>
        <div data-bgColor="dark"></div>
        <p>#afbac4</p>
      </li>
      <li>
        <div data-bgColor="gray"></div>
        <p>#bbc1c6</p>
      </li>
      <li>
        <div data-bgColor="light"></div>
        <p>#e3e5e9</p>
      </li>
      <li>
        <div data-bgColor="lightest"></div>
        <p>#f7f9fc</p>
      </li>
      <li>
        <div data-bgColor="red"></div>
        <p>#e25d43</p>
      </li>
    </ul>
  </section>
  <section class="sg-section" id="typography">
    <h3 class="beta">02. Typography</h3>
    <div class="sg-inlineblock">
      <h4>Glyph</h4>
      <p class="giga">Aa</p>
    </div>
    <div class="sg-inlineblock sg-weights">
      <h4>Weights</h4>
      <ul class="bare-list">
        <li>Regular</li>
        <li><em>Regular Italic</em></li>
        <li><strong>Bold</strong></li>
        <li><strong><em>Bold Italic</em></strong></li>
      </ul>
    </div>
    <table class="table--lines sg-typotable">
      <thead>
        <tr>
          <th>Style</th>
          <th>Desktop</th>
          <th>Tablet</th>
          <th>Mobile</th>
          <th>Line-height</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td class="alpha">H1 / .alpha</td>
          <td>48px</td>
          <td>40px</td>
          <td>36px</td>
          <td>1.2</td>
        </tr>
        <tr>
          <td class="beta">H2 / .beta</td>
          <td>36px</td>
          <td>32px</td>
          <td>28px</td>
          <td>1.2</td>
        </tr>
        <tr>
          <td class="gamma">H3 / .gamma</td>
          <td>28px</td>
          <td>28px</td>
          <td>24px</td>
          <td>1.2</td>
        </tr>
        <tr>
          <td class="delta">H4 / .delta</td>
          <td>13px</td>
          <td>13px</td>
          <td>13px</td>
          <td>1.5</td>
        </tr>
        <tr>
          <td class="epsilon">H5 / .epsilon</td>
          <td>14px</td>
          <td>14px</td>
          <td>14px</td>
          <td>1.4</td>
        </tr>
        <tr>
          <td class="zeta">H6 / .zeta</td>
          <td>12px</td>
          <td>12px</td>
          <td>12px</td>
          <td>1.4</td>
        </tr>
        <tr>
          <td class="sg-header-button">Action/Button</td>
          <td>13px</td>
          <td>13px</td>
          <td>13px</td>
          <td>1</td>
        </tr>
        <tr>
          <td>Paragraph text</td>
          <td>15px</td>
          <td>15px</td>
          <td>15px</td>
          <td>1.6</td>
        </tr>
      </tbody>
    </table>
  </section>
  <section class="sg-section" id="buttons">
    <h3 class="beta">03. Buttons</h3>
    <h4>Default button</h4>
    <div>
      <%= render(partial:'simple_boutton',locals:{label:'buttone'}) %>
      <%= render(partial:'bouton_link',locals:{label:'link'}) %>
    </div>
    <h4>Primary button</h4>
    <div>
        <%= render(partial:'primary_boutton',locals:{label:'Primary'}) %>
    </div>
    <h4>Negative button</h4>
    <div>
      <%= render(partial:'warning_boutton',locals:{label:'warning'}) %>
    </div>
  </section>
  <section class="sg-section" id="forms">
    <h3 class="beta">04. Form Elements</h3>
    <div>
      <h4 class="gamma">Input field</h4>
      <div class="input-group input-group--horizontal">
        <label class="input-group__label" for="sg-input">Input label</label>
        <input id="sg-input" class="input-group__field" type="text" name="sg-input" placeholder="Placeholder text">
      </div>
    </div>
    <div>
      <h4 class="gamma">Text area</h4>
      <div class="input-group input-group--horizontal">
        <label class="input-group__label" for="sg-textarea">Text area label</label>
        <textarea id="sg-textarea" class="input-group__field"></textarea>
      </div>
    </div>
    <div>
      <h4 class="gamma">Validation message on 1 column form</h4>
      <div class="alert">
        Please fill out a valid email address.
        <p>Please enter name.</p>
        <ul>
          <li>Phone number missing.</li>
          <li>Postcode missing.</li>
        </ul>
      </div>
    </div>
    <div>
      <h4 class="gamma">Validation message on 2 column form</h4>
      <div class="alert alert--wide">
        Please fill out a valid email address.
        <p>Please enter name.</p>
        <ul>
          <li>Phone number missing.</li>
          <li>Postcode missing.</li>
        </ul>
      </div>
    </div>
  </section>
  <section class="sg-section" id="icons">
    <h3 class="beta">05. Icons</h3>
    <div>
      <ul>
        <li>
          <svg class="icon-heart" role="presentation">
            <use xlink:href="/images/icons/icons-defs.svg"></use>
          </svg>
        </li>
        <li>
          <svg class="icon-heart icon-heart--liked" role="presentation">
            <use xlink:href="/images/icons/icons-defs.svg"></use>
          </svg>
        </li>
        <li>
          <svg class="icon-pluss" role="presentation">
            <use xlink:href="/images/icons/icons-defs.svg"></use>
          </svg>
        </li>
        <li>
          <svg class="icon-edit" role="presentation">
            <use xlink:href="/images/icons/icons-defs.svg"></use>
          </svg>
        </li>
        <li>
          <svg class="icon-delete" role="presentation">
            <use xlink:href="/images/icons/icons-defs.svg"></use>
          </svg>
        </li>
        <li>
          <svg class="icon-edit" role="presentation">
            <use xlink:href="/images/icons/icons-defs.svg"></use>
          </svg>
        </li>
      </ul>
    </div>
  </section>
</main>

app/views/users/new.html.erb
<main>
  <section class="envelope">
    <header class="text--center">
      <h1 class="gamma">Sign up / Log in</h1>
    </header>
    <main>
        <%=form_for(@user) do |form| %>
        <div class="input-group">

          <%=form.label(:email,class: "input-group__label") %>
          <%=form.text_field(:email, class: "input-group__field",placeholder: "e.g. me@epfl.ch" ) %>
        </div>
        <div class="prompt">
          <%=form.submit("log in",class: "btn btn--primary prompt__confirm") %>
        </div>
    <% end %>
    </main>
  </section>
</main>